const API_URL="https://script.google.com/macros/s/AKfycbzPKVS_IYR6ImVRVXY159hC6L5reGkOxuNADIKdnrUw2l7CWXwxeIcjjNATWE6OzQgz/exec";
const state={settings:{},students:[],homework:[],subjectOptions:{},custom:[],scanner:null,scanLocked:false};

document.addEventListener("DOMContentLoaded",()=>{bind();setToday();loadInitial()});

function el(id){return document.getElementById(id)}
function bind(){
 document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
 document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>selectSubject(b.dataset.subject)));
 el("refreshBtn").addEventListener("click",loadInitial);
 el("lessonSelect").addEventListener("change",renderTypes);
 el("addCustomHomeworkBtn").addEventListener("click",addCustom);
 el("customHomeworkInput").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();addCustom()}});
 el("homeworkForm").addEventListener("submit",createHomework);
 el("scanHomeworkSelect").addEventListener("change",updateSelected);
 el("startScanBtn").addEventListener("click",startScanner);
 el("stopScanBtn").addEventListener("click",stopScanner);
 el("manualSubmitBtn").addEventListener("click",manualSubmit);
 el("manualQrInput").addEventListener("keydown",e=>{if(e.key==="Enter")manualSubmit()});
 el("loadRecordBtn").addEventListener("click",loadDetail);
 el("settingsForm").addEventListener("submit",saveSettings);
}
function setToday(){const d=new Date();el("todayDate").textContent=`${d.getMonth()+1}/${d.getDate()}`;el("dueDateInput").value=localDate(d)}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));el(id).classList.add("active");if(id!=="scanView")stopScanner();window.scrollTo({top:0,behavior:"smooth"})}
function selectSubject(subject){el("subjectSelect").value=subject;document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.subject===subject));state.custom=[];renderCustom();renderForm()}
async function loadInitial(){msg("正在載入資料……","warning");try{const d=await jsonp("initial");if(!d.ok)throw new Error(d.message||"資料載入失敗");state.settings=d.settings||{};state.students=d.students||[];state.homework=d.homework||[];state.subjectOptions=d.subjectOptions||{};el("classInfo").textContent=`${state.settings["班級"]||"未設定班級"}｜${state.settings["老師"]||"未設定老師"}老師`;el("studentCount").textContent=state.students.length;el("defaultDueTimeInput").value=time(state.settings["預設截止時間"])||"16:00";el("classNameInput").value=state.settings["班級"]||"";el("teacherNameInput").value=state.settings["老師"]||"";renderForm();renderToday();renderSelectors();hideMsg()}catch(e){msg("無法連接系統："+e.message,"error")}}
function renderForm(){const s=el("subjectSelect").value;const lessonMode=s==="國語"||s==="數學";el("lessonField").classList.toggle("hidden",!lessonMode);el("presetField").classList.toggle("hidden",s==="自行加入");el("customField").classList.toggle("hidden",!(s==="其他"||s==="自行加入"));const ls=el("lessonSelect");ls.innerHTML="";if(lessonMode){const count=s==="國語"?16:10;for(let i=1;i<=count;i++)ls.add(new Option(`第${i}課`,i))}else ls.add(new Option("不分課次",0));el("dueTimeInput").value=time(state.settings["預設截止時間"])||"16:00";renderTypes();renderCustom()}
function renderTypes(){const s=el("subjectSelect").value,l=Number(el("lessonSelect").value||1);let types=[];if(s==="國語"){types=["考卷","習作","考試本","圈詞本","造句本","預習單","國綜",l%2?"甲本":"乙本"]}else if(s==="數學"){types=["考卷","習作","數練","數八格"]}else if(s==="其他"){types=["聯絡本","學習單","回條"]}el("homeworkTypeOptions").innerHTML=types.map(t=>`<label class="check"><input type="checkbox" name="type" value="${esc(t)}"><span>${esc(t)}</span></label>`).join("")}
function addCustom(){const v=el("customHomeworkInput").value.trim();if(!v)return msg("請先輸入作業名稱。","error");if(!state.custom.includes(v))state.custom.push(v);el("customHomeworkInput").value="";renderCustom()}
function renderCustom(){el("customHomeworkList").innerHTML=state.custom.map((t,i)=>`<span class="tag">${esc(t)}<button type="button" onclick="removeCustom(${i})">×</button></span>`).join("")}
function removeCustom(i){state.custom.splice(i,1);renderCustom()}
async function createHomework(e){e.preventDefault();const s=el("subjectSelect").value;const checked=[...document.querySelectorAll('input[name="type"]:checked')].map(x=>x.value);let types=s==="自行加入"?[...state.custom]:[...checked,...(s==="其他"?state.custom:[])];const direct=el("customHomeworkInput").value.trim();if((s==="其他"||s==="自行加入")&&direct)types.push(direct);types=[...new Set(types.map(x=>x.trim()).filter(Boolean))];if(!types.length)return msg((s==="其他"||s==="自行加入")?"請勾選或輸入至少一項作業。":"請至少勾選一項作業。","error");const btn=el("createHomeworkBtn");btn.disabled=true;btn.textContent="建立中……";try{const backendSubject=s==="自行加入"?"其他":s;for(const type of types){const r=await jsonp("createHomework",{subject:backendSubject,lesson:el("lessonSelect").value||0,type,dueDate:el("dueDateInput").value,dueTime:el("dueTimeInput").value});if(!r.ok)throw new Error(r.message||`${type} 建立失敗`)}msg(`已建立 ${types.length} 項作業。`,"success");state.custom=[];el("customHomeworkInput").value="";renderCustom();await loadInitial();showView("homeView")}catch(err){msg(err.message,"error")}finally{btn.disabled=false;btn.textContent="建立今天作業"}}
function label(h){if(h.subject==="自行加入")return h.type;if(h.subject==="其他")return `其他｜${h.type}`;return `${h.subject} 第${h.lesson}課｜${h.type}`}
function todayItems(){const t=localDate(new Date());return state.homework.filter(h=>h.enabled&&date(h.dueDate)===t)}
function renderToday(){const items=todayItems();el("todayHomeworkCount").textContent=items.length;el("todayHomeworkList").innerHTML=items.length?items.map(h=>`<article class="homework-item"><div><h3>${esc(label(h))}</h3><p>截止：${esc(date(h.dueDate))} ${esc(time(h.dueTime))}</p></div><span class="pill success">收件中</span></article>`).join(""):'<p class="empty">目前尚未建立今日作業。</p>'}
function renderSelectors(){const items=[...state.homework].filter(h=>h.enabled).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const html=items.length?items.map(h=>`<option value="${esc(h.homeworkId)}">${esc(`${date(h.dueDate)}｜${label(h)}`)}</option>`).join(""):'<option value="">目前沒有作業</option>';el("scanHomeworkSelect").innerHTML=html;el("recordHomeworkSelect").innerHTML=html;updateSelected()}
function updateSelected(){const h=state.homework.find(x=>x.homeworkId===el("scanHomeworkSelect").value);el("selectedHomeworkCard").innerHTML=h?`<strong>${esc(label(h))}</strong><br>截止：${esc(date(h.dueDate))} ${esc(time(h.dueTime))}`:"目前沒有作業。"}
async function startScanner(){if(!el("scanHomeworkSelect").value)return msg("目前沒有可掃描的作業。","error");if(!window.Html5Qrcode)return msg("掃描套件尚未載入。","error");el("qrReader").classList.remove("hidden");el("startScanBtn").classList.add("hidden");el("stopScanBtn").classList.remove("hidden");state.scanner=new Html5Qrcode("qrReader");try{await state.scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:230,height:230}},async text=>{if(state.scanLocked)return;state.scanLocked=true;await submitQr(text.trim());setTimeout(()=>state.scanLocked=false,1600)},()=>{})}catch(e){msg("相機無法開啟："+e.message,"error");stopScanner()}}
async function stopScanner(){if(state.scanner){try{if(state.scanner.isScanning)await state.scanner.stop();await state.scanner.clear()}catch(_){ }state.scanner=null}el("qrReader").innerHTML="";el("qrReader").classList.add("hidden");el("startScanBtn").classList.remove("hidden");el("stopScanBtn").classList.add("hidden")}
function manualSubmit(){const q=el("manualQrInput").value.trim();if(!q)return msg("請輸入學生 QR 編號。","error");submitQr(q);el("manualQrInput").value=""}
async function submitQr(qrCode){try{const r=await jsonp("submit",{qrCode,homeworkId:el("scanHomeworkSelect").value});el("scanResult").classList.remove("hidden");el("scanResult").className=`scan-result ${r.ok?"success":"danger"}`;el("scanResult").innerHTML=r.ok?`<strong>${esc(r.student.name)}</strong><br>${esc(r.submissionStatus)}`:esc(r.message||"登記失敗")}catch(e){msg(e.message,"error")}}
async function loadDetail(){const id=el("recordHomeworkSelect").value;if(!id)return msg("請先選擇作業。","error");try{const r=await jsonp("homeworkDetail",{homeworkId:id});if(!r.ok)throw new Error(r.message||"讀取失敗");el("recordSummary").classList.remove("hidden");el("recordSummary").innerHTML=`<article><span>已交</span><strong>${r.summary.submitted}</strong></article><article><span>遲交</span><strong>${r.summary.late}</strong></article><article><span>未交</span><strong>${r.summary.missing}</strong></article>`;el("studentRecordPanel").classList.remove("hidden");el("recordTitle").innerHTML=`<h2>${esc(label(r.homework))}</h2>`;el("studentRecordBody").innerHTML=r.students.map(s=>`<tr><td>${esc(s.seatNo)}</td><td>${esc(s.name)}</td><td>${esc(s.submissionStatus)}</td><td>${esc(s.correctionStatus)}</td><td>${s.submissionStatus==="未交"?"—":`<button class="small-btn" onclick="toggleCorrection('${js(s.qrCode)}','${js(r.homework.homeworkId)}',${s.correctionStatus!=="已訂正"})">${s.correctionStatus==="已訂正"?"改為未訂正":"標記已訂正"}</button>`}</td></tr>`).join("")}catch(e){msg(e.message,"error")}}
async function toggleCorrection(qrCode,homeworkId,corrected){const r=await jsonp("markCorrection",{qrCode,homeworkId,corrected:String(corrected)});if(!r.ok)return msg(r.message||"更新失敗","error");loadDetail()}
async function saveSettings(e){e.preventDefault();try{const r=await jsonp("updateSettings",{className:el("classNameInput").value.trim(),teacherName:el("teacherNameInput").value.trim(),defaultDueTime:el("defaultDueTimeInput").value});if(!r.ok)throw new Error(r.message||"儲存失敗");await loadInitial();showView("homeView")}catch(err){msg(err.message,"error")}}
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb=`cb_${Date.now()}_${Math.floor(Math.random()*9999)}`;const s=document.createElement("script");const timer=setTimeout(()=>{cleanup();reject(new Error("連線逾時，請檢查 Apps Script 部署。"))},20000);function cleanup(){clearTimeout(timer);delete window[cb];s.remove()}window[cb]=d=>{cleanup();resolve(d)};s.src=`${API_URL}?${new URLSearchParams({action,callback:cb,...params})}`;s.onerror=()=>{cleanup();reject(new Error("無法連接 Apps Script。"))};document.body.appendChild(s)})}
function msg(t,type="success"){el("messageBox").textContent=t;el("messageBox").className=`message ${type}`}function hideMsg(){el("messageBox").className="message hidden"}
function date(v){const m=String(v||"").match(/(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`:String(v||"")}
function time(v){const m=String(v||"").match(/(\d{1,2}):(\d{2})/);return m?`${m[1].padStart(2,"0")}:${m[2]}`:String(v||"")}
function localDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function js(v){return String(v??"").replaceAll("\\","\\\\").replaceAll("'","\\'")}
