const API_URL="https://script.google.com/macros/s/AKfycbzPKVS_IYR6ImVRVXY159hC6L5reGkOxuNADIKdnrUw2l7CWXwxeIcjjNATWE6OzQgz/exec";
const state={settings:{},students:[],homework:[],subjectOptions:{},scanner:null,scanLocked:false};

document.addEventListener("DOMContentLoaded",()=>{bindEvents();setToday();loadInitialData()});

function bindEvents(){
 document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));
 refreshBtn.addEventListener("click",loadInitialData);
 subjectSelect.addEventListener("change",updateHomeworkForm);
 lessonSelect.addEventListener("change",renderHomeworkTypes);
 homeworkForm.addEventListener("submit",createHomework);
 scanHomeworkSelect.addEventListener("change",updateSelectedHomeworkCard);
 startScanBtn.addEventListener("click",startScanner);
 stopScanBtn.addEventListener("click",stopScanner);
 manualSubmitBtn.addEventListener("click",submitManualQr);
 manualQrInput.addEventListener("keydown",e=>{if(e.key==="Enter")submitManualQr()});
 loadRecordBtn.addEventListener("click",loadHomeworkDetail);
 settingsForm.addEventListener("submit",saveSettings)
}
function setToday(){const n=new Date();todayDate.textContent=new Intl.DateTimeFormat("zh-TW",{month:"numeric",day:"numeric"}).format(n);dueDateInput.value=toLocalDateString(n)}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.getElementById(id).classList.add("active");if(id!=="scanView")stopScanner();if(id==="recordsView")renderHomeworkSelectors();window.scrollTo({top:0,behavior:"smooth"})}
async function loadInitialData(){showMessage("正在載入資料……","warning");try{const d=await jsonp("initial");if(!d.ok)throw new Error(d.message||"資料載入失敗");Object.assign(state,{settings:d.settings||{},students:d.students||[],homework:d.homework||[],subjectOptions:d.subjectOptions||{}});renderHeader();updateHomeworkForm();renderTodayHomework();renderHomeworkSelectors();fillSettingsForm();hideMessage()}catch(e){showMessage("無法連接系統："+e.message,"error")}}
function renderHeader(){classInfo.textContent=`${state.settings["班級"]||"未設定班級"}｜${state.settings["老師"]||"未設定老師"}老師`;studentCount.textContent=state.students.length}
function updateHomeworkForm(){const s=subjectSelect.value,o=state.subjectOptions[s]||{},n=Number(o.lessonCount||(s==="國語"?16:10));lessonSelect.innerHTML="";for(let i=1;i<=n;i++)lessonSelect.add(new Option(`第${i}課`,i));dueTimeInput.value=normalizeTime(state.settings["預設截止時間"])||"16:00";renderHomeworkTypes()}
function renderHomeworkTypes(){const s=subjectSelect.value,l=Number(lessonSelect.value||1),types=[...(state.subjectOptions[s]?.commonTypes||[])];if(s==="國語")types.push(l%2===1?"甲本":"乙本");homeworkTypeOptions.innerHTML=types.map(t=>`<label class="check-option"><input type="checkbox" name="homeworkType" value="${escapeHtml(t)}"><span>${escapeHtml(t)}</span></label>`).join("")}
async function createHomework(e){e.preventDefault();const btn=createHomeworkBtn,types=[...document.querySelectorAll('input[name="homeworkType"]:checked')].map(i=>i.value);if(!types.length)return showMessage("請至少勾選一種作業類型。","error");const p={subject:subjectSelect.value,lesson:lessonSelect.value,dueDate:dueDateInput.value,dueTime:dueTimeInput.value};btn.disabled=true;btn.textContent="建立中……";try{for(const type of types){const r=await jsonp("createHomework",{...p,type});if(!r.ok)throw new Error(r.message||`${type}建立失敗`)}showMessage(`已建立 ${types.length} 份作業。`,"success");await loadInitialData();showView("homeView")}catch(err){showMessage(err.message,"error")}finally{btn.disabled=false;btn.textContent="建立作業"}}
function getTodayHomework(){const t=toLocalDateString(new Date());return state.homework.filter(i=>i.enabled&&normalizeDate(i.dueDate)===t)}
function renderTodayHomework(){const h=getTodayHomework();todayHomeworkCount.textContent=h.length;todayHomeworkList.innerHTML=h.length?h.map(i=>`<article class="homework-item"><div><h3>${escapeHtml(i.subject)} 第${i.lesson}課｜${escapeHtml(i.type)}</h3><p>截止：${escapeHtml(normalizeDate(i.dueDate))} ${escapeHtml(normalizeTime(i.dueTime))}</p></div><span class="status-pill status-success">收件中</span></article>`).join(""):'<div class="empty-state">目前尚未建立今日作業。</div>'}
function renderHomeworkSelectors(){const a=[...state.homework].filter(i=>i.enabled).sort((x,y)=>String(y.createdAt).localeCompare(String(x.createdAt)));const o=a.length?a.map(i=>`<option value="${escapeHtml(i.homeworkId)}">${escapeHtml(`${normalizeDate(i.dueDate)}｜${i.subject} 第${i.lesson}課 ${i.type}`)}</option>`).join(""):'<option value="">目前沒有作業</option>';scanHomeworkSelect.innerHTML=o;recordHomeworkSelect.innerHTML=o;updateSelectedHomeworkCard()}
function updateSelectedHomeworkCard(){const i=state.homework.find(h=>h.homeworkId===scanHomeworkSelect.value);selectedHomeworkCard.innerHTML=i?`<strong>${escapeHtml(i.subject)} 第${i.lesson}課｜${escapeHtml(i.type)}</strong><br>截止：${escapeHtml(normalizeDate(i.dueDate))} ${escapeHtml(normalizeTime(i.dueTime))}`:"請先建立並選擇一份作業。"}
async function startScanner(){if(!scanHomeworkSelect.value)return showMessage("目前沒有可掃描的作業。","error");if(!window.Html5Qrcode)return showMessage("掃描套件尚未載入，請重新整理頁面。","error");qrReader.classList.remove("hidden");startScanBtn.classList.add("hidden");stopScanBtn.classList.remove("hidden");state.scanner=new Html5Qrcode("qrReader");try{await state.scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:240,height:240}},async text=>{if(state.scanLocked)return;state.scanLocked=true;await submitQr(text.trim());setTimeout(()=>state.scanLocked=false,1700)},()=>{})}catch(e){showMessage("相機無法開啟："+e.message,"error");await stopScanner()}}
async function stopScanner(){if(state.scanner){try{if(state.scanner.isScanning)await state.scanner.stop();await state.scanner.clear()}catch(_){}state.scanner=null}if(window.qrReader){qrReader.innerHTML="";qrReader.classList.add("hidden")}startScanBtn?.classList.remove("hidden");stopScanBtn?.classList.add("hidden")}
function submitManualQr(){const q=manualQrInput.value.trim();if(!q)return showMessage("請輸入學生 QR 編號。","error");submitQr(q);manualQrInput.value="";manualQrInput.focus()}
async function submitQr(qrCode){const homeworkId=scanHomeworkSelect.value;if(!homeworkId)return showMessage("請先選擇作業。","error");scanResult.className="scan-result warning";scanResult.textContent="登記中……";try{const r=await jsonp("submit",{qrCode,homeworkId});if(r.ok){const late=r.submissionStatus==="遲交";scanResult.className=`scan-result ${late?"warning":"success"}`;scanResult.innerHTML=`<strong>${escapeHtml(r.student.name)}</strong><br>${escapeHtml(r.submissionStatus)}`;playBeep(late?420:700)}else{scanResult.className="scan-result error";scanResult.textContent=r.message||"登記失敗";playBeep(230)}}catch(e){scanResult.className="scan-result error";scanResult.textContent=e.message}}
async function loadHomeworkDetail(){const homeworkId=recordHomeworkSelect.value;if(!homeworkId)return showMessage("請先選擇一份作業。","error");showMessage("正在讀取紀錄……","warning");try{const r=await jsonp("homeworkDetail",{homeworkId});if(!r.ok)throw new Error(r.message||"讀取失敗");recordSummary.classList.remove("hidden");recordSummary.innerHTML=`<article class="summary-card"><span>已交</span><strong>${r.summary.submitted}</strong></article><article class="summary-card"><span>遲交</span><strong>${r.summary.late}</strong></article><article class="summary-card"><span>未交</span><strong>${r.summary.missing}</strong></article>`;studentRecordPanel.classList.remove("hidden");recordTitle.innerHTML=`<div><p class="eyebrow">HOMEWORK DETAIL</p><h2>${escapeHtml(r.homework.subject)} 第${r.homework.lesson}課｜${escapeHtml(r.homework.type)}</h2></div>`;studentRecordBody.innerHTML=r.students.map(s=>{const c=s.submissionStatus==="已交"?"status-success":s.submissionStatus==="遲交"?"status-warning":"status-danger",can=s.submissionStatus!=="未交",done=s.correctionStatus==="已訂正";return `<tr><td>${escapeHtml(s.seatNo)}</td><td>${escapeHtml(s.name)}</td><td><span class="status-pill ${c}">${escapeHtml(s.submissionStatus)}</span></td><td>${escapeHtml(s.correctionStatus)}</td><td>${can?`<button class="correction-button" type="button" onclick="toggleCorrection('${escapeJs(s.qrCode)}','${escapeJs(r.homework.homeworkId)}',${!done})">${done?"改為未訂正":"標記已訂正"}</button>`:"—"}</td></tr>`}).join("");hideMessage()}catch(e){showMessage(e.message,"error")}}
async function toggleCorrection(qrCode,homeworkId,corrected){try{const r=await jsonp("markCorrection",{qrCode,homeworkId,corrected:String(corrected)});if(!r.ok)throw new Error(r.message||"更新失敗");showMessage(r.message,"success");await loadHomeworkDetail()}catch(e){showMessage(e.message,"error")}}
function fillSettingsForm(){classNameInput.value=state.settings["班級"]||"";teacherNameInput.value=state.settings["老師"]||"";defaultDueTimeInput.value=normalizeTime(state.settings["預設截止時間"])||"16:00"}
async function saveSettings(e){e.preventDefault();try{const r=await jsonp("updateSettings",{className:classNameInput.value.trim(),teacherName:teacherNameInput.value.trim(),defaultDueTime:defaultDueTimeInput.value});if(!r.ok)throw new Error(r.message||"儲存失敗");showMessage("設定已儲存。","success");await loadInitialData();showView("homeView")}catch(err){showMessage(err.message,"error")}}
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb=`jsonpCallback_${Date.now()}_${Math.floor(Math.random()*10000)}`,s=document.createElement("script"),timer=setTimeout(()=>{clean();reject(new Error("連線逾時，請檢查 Apps Script 部署權限。"))},20000);function clean(){clearTimeout(timer);delete window[cb];s.remove()}window[cb]=d=>{clean();resolve(d)};s.src=`${API_URL}?${new URLSearchParams({action,callback:cb,...params})}`;s.onerror=()=>{clean();reject(new Error("無法連接 Apps Script。"))};document.body.appendChild(s)})}
function showMessage(t,type="success"){messageBox.textContent=t;messageBox.className=`message ${type}`}function hideMessage(){messageBox.className="message hidden"}
function normalizeDate(v){const t=String(v||"").trim(),m=t.match(/(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`:t}
function normalizeTime(v){const t=String(v||"").trim(),m=t.match(/(\d{1,2}):(\d{2})/);return m?`${m[1].padStart(2,"0")}:${m[2]}`:t}
function toLocalDateString(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function escapeJs(v){return String(v??"").replaceAll("\\","\\\\").replaceAll("'","\\'")}
function playBeep(f){try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.08;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.12)}catch(_){}}
